name: Continous Integration

on:
  pull_request:
    branches: [$default_branch]
  push:
    branches: [$default_branch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

# Waiting for API key approval

#      - name: Run Tests
#       run: yarn coverage

      - name: Build
        run: yarn build
