blank_issues_enabled: false
contact_links:
  - name: Discord server
    url: https://discord.gg/DDTmaeYUMF
    about: Please visit our Discord server for questions and support requests.
  - name: Owner
    url: https://discord.com/users/712560683216011274
