name: Continuous Integration
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  Continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2
      - name: Use Node.js
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # v2
        with:
          node-version: 16
      - name: Restore CI Cache
        uses: actions/cache@4723a57e26efda3a62cbde1812113b730952852d # v3
        id: cache-restore
        with:
          path: node_modules
          key: ${{ runner.os }}-16-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies if Cache Miss
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        run: yarn --immutable

      - name: Check Liniting
        run: yarn lint

      - name: Run Tests
        if: ${{ github.event_name == 'push' }}
        env:
          VITE_HYPIXEL_API_KEY: '${{ secrets.HYPIXEL_API_KEY }}'
        run: yarn coverage

      - name: Build Code
        run: yarn build
